 airport          => "../../destinations/code/symbols/airport.svg",   
 bus              => "../../destinations/code/symbols/bus.png",
 camp_site        => "../../destinations/code/symbols/camp_site.svg",
 center           => "../../destinations/code/symbols/centre.png",
 centre           => "../../destinations/code/symbols/centre.png",
 church           => "../../destinations/code/symbols/church.png",
 covered_parking  => "../../destinations/code/symbols/covered_parking.svg",
 ferry            => "../../destinations/code/symbols/ferry.svg",
 fuel             => "../../destinations/code/symbols/fuel.svg",  
 funicular        => "../../destinations/code/symbols/funicular.svg",  
 food             => "../../destinations/code/symbols/restaurant.svg",
 harbour          => "../../destinations/code/symbols/ferry.svg",
 hospital         => "../../destinations/code/symbols/hospital.svg", 
 hotel            => "../../destinations/code/symbols/hotel.svg",
 industrial       => "../../destinations/code/symbols/industrial.svg",
 information      => "../../destinations/code/symbols/information.svg", 
 lodging          => "../../destinations/code/symbols/lodging.svg",
 motorroad        => "../../destinations/code/symbols/motorroad.svg", 
 motorway         => "../../destinations/code/symbols/motorway.svg", 
 park_and_ride    => "../../destinations/code/symbols/park_and_ride.svg",  
 parking          => "../../destinations/code/symbols/parking.svg",  
 police           => "../../destinations/code/symbols/police.svg",
 rest_area        => "../../destinations/code/symbols/parking.svg",   
 restaurant       => "../../destinations/code/symbols/restaurant.svg", 
 stadium          => "../../destinations/code/symbols/stadium.svg", 
 soccer_stadium   => "../../destinations/code/symbols/stadium.svg", 
 swimming         => "../../destinations/code/symbols/swimming.svg", 
 toilets          => "../../destinations/code/symbols/toilets.svg", 
 train_station    => "../../destinations/code/symbols/train_station.svg", 
 viewpoint        => "../../destinations/code/symbols/viewpoint.svg", 




